# This workflow will build a docker container

name: Building docker image

on:
  push:
    branches: [master]

jobs:
  setup-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:

    # Build the Docker image
    - name: Build
      run: |        
        docker build -t ric-script-nodejs-app:1.0 .
