name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - uses: BSFishy/meson-build@v1.0.1
      with:
        action: build
    - id: build-meson
      run: meson builddir; cd builddir; ninja
  test:

    runs-on: ubuntu-latest
    steps:
    - id: pytests
      uses: fylein/python-pytest-github-action@v1
      with:
        args: pip3 install -r tests/requirements.txt; cd tests; pytest


