name: Memory leakage detection

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build project
      run: make
    - name: Update packet manager
      run: sudo apt-get update
    - name: Install Valgrind
      run: sudo apt-get install valgrind
    - name: Run valgrind on example.ric
      run: valgrind --leak-check=full ./ric samples/example.ric
    - name: Run valgrind on vector_print.ric
      run: valgrind --leak-check=full ./ric samples/vector_print.ric
    - name: Run valgrind on func_ptr.ric
      run: valgrind --leak-check=full ./ric samples/func_ptr.ric
    - name: Run valgrind on function_within_function.ric
      run: valgrind --leak-check=full ./ric samples/function_within_function.ric
    - name: Run valgrind on gcd.ric
      run: valgrind --leak-check=full ./ric samples/gcd.ric 21390 3210
    - name: Run valgrind on demo.ric
      run: valgrind --leak-check=full ./ric samples/demo.ric

